const { test } = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')
const vm = require('node:vm')
const read = file => readFileSync(path.join(__dirname, '../src', file), 'utf8')
const context = vm.createContext({})
vm.runInContext(read('utils/taskCategory.js').replace(/export /g, '') + '\nglobalThis.matchesTab = taskMatchesTab', context)
vm.runInContext(read('utils/dateTime.js').replace(/export /g, '') + '\nglobalThis.format = formatDateTime', context)
test('UTC completion timestamps become Beijing 24-hour times without shifting local deadlines', () => {
  assert.equal(context.format('2026-10-01T07:36:00Z'), '2026-10-01 15:36')
  assert.equal(context.format('2026-10-01T16:00:00Z'), '2026-10-02 00:00')
  assert.equal(context.format('2026-10-01T15:36:00'), '2026-10-01 15:36')
  assert.equal(context.format(''), '')
})
test('all leave mutations use campus-compatible POST', () => {
  assert.doesNotMatch(read('api/leave.js'), /method: '(put|delete)'/)
})
test('all requested political statuses and task audience identities share one ordered source', () => {
  const options = read('constants/politicalStatus.js')
  assert.ok(options.indexOf('发展对象') < options.indexOf('入党积极分子'))
  for (const file of ['views/Profile.vue', 'views/admin/DailyControl.vue', 'views/admin/ActivityManagement.vue'])
    assert.match(read(file), /POLITICAL_STATUS_OPTIONS/)
  assert.doesNotMatch(options, /民主党派/)
})
test('students and administrators have honor edit/delete actions and homepage completion', () => {
  for (const file of ['views/Daily.vue', 'views/admin/DailyControl.vue']) {
    assert.match(read(file), /updateItem\('honor'/)
    assert.match(read(file), /deleteItem\('honor'/)
  }
  assert.match(read('views/Home.vue'), /普通任务完成度/)
  assert.match(read('views/admin/Dashboard.vue'), /getTaskCompletionAnalysis/)
})
test('task handouts, daily-task classification and upload guard are wired into publishing', () => {
  const source = read('views/admin/DailyControl.vue')
  assert.match(source, /日常任务/)
  assert.match(source, /value="routine"/)
  assert.match(source, /if \(taskAttachmentUploading.value\)/)
  const activity = read('views/admin/ActivityManagement.vue')
  assert.match(activity, /value="routine"/)
  assert.match(activity, /v-model="activityForm.attachments"/)
  assert.match(activity, /attachments: JSON.parse\(activityForm.attachments/)
  for (const file of ['views/Home.vue', 'views/Daily.vue']) assert.match(read(file), /attachments/)
})
test('routine tasks and homepage links reach the student task list instead of an undefined route', () => {
  for (const activityCategory of ['daily', 'routine', undefined]) assert.equal(context.matchesTab({activityCategory}, 'tasks'), true)
  for (const activityCategory of ['academic', 'volunteer']) assert.equal(context.matchesTab({activityCategory}, 'tasks'), false)
  assert.match(read('views/Daily.vue'), /!\['daily', 'routine'\].includes\(category\)/)
})
